# Generated by Django 4.1.7 on 2023-06-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
